import Link from "next/link";
import { ArrowUpRight, Check, ShieldCheck, Activity, DatabaseZap, ArrowDownRight, CircleDashed, LockKeyhole } from "lucide-react";

export default function Home() {
  return <>
    <section className="hero home-hero"><div className="container hero-grid"><div><p className="eyebrow">Payment trust infrastructure <span className="eyebrow-rule" /></p><h1>The control plane for <em>money in motion.</em></h1><p className="lede">PesaGuard gives African payment teams one dependable place to reconcile, monitor, and protect every transaction.</p><div className="actions"><Link className="button button-primary" href="/contact/sales">Talk to our team <ArrowUpRight size={17} /></Link><Link className="button button-quiet" href="/product">Explore the platform</Link></div><div className="hero-proof"><span><Check size={14} /> Built for payment operations</span><span><Check size={14} /> Designed around evidence</span></div></div><div className="signal-panel" aria-label="Payment operations preview"><div className="panel-top"><span className="status-dot" /> Live operations <span>Today, 09:42 EAT</span></div><div className="signal-number">98.7<span>%</span></div><p>records reconciled automatically</p><div className="bar"><i style={{ width: "82%" }} /></div><div className="signal-list"><div><span className="icon-box"><Check size={15} /></span><span>Settlement matched<small>M-Pesa · 2 min ago</small></span><strong>+ KES 284,500</strong></div><div><span className="icon-box amber"><Activity size={15} /></span><span>Review signal<small>Duplicate reference detected</small></span><strong className="amber-text">Needs review</strong></div><div><span className="icon-box blue"><ShieldCheck size={15} /></span><span>Risk controls active<small>All channels monitored</small></span><strong>Protected</strong></div></div><div className="panel-foot"><span>Connected channels</span><span className="channel-dots"><i /> <i /> <i /> <i /> <b>+12</b></span></div></div></div></section>
    <section className="trust-strip"><div className="container trust-row"><span>Built for teams moving money across</span><b>mobile money</b><b>bank rails</b><b>merchant networks</b><b>digital finance</b></div></section>
    <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">The operating layer</p><h2>Make payment complexity feel manageable.</h2><p>One clear view across the systems, exceptions, and controls your operation depends on.</p></div><div className="feature-grid"><article className="feature-card"><DatabaseZap /><span className="card-index">01</span><h3>Reconcile with context</h3><p>Match records across providers and settlement files while keeping the evidence your team needs.</p><Link href="/features/reconciliation">Explore reconciliation <ArrowUpRight size={16} /></Link></article><article className="feature-card feature-card-dark"><Activity /><span className="card-index">02</span><h3>Spot what changed</h3><p>Monitor transaction flows, data quality, and risk signals before they become expensive surprises.</p><Link href="/features/transaction-monitoring">Explore monitoring <ArrowUpRight size={16} /></Link></article><article className="feature-card"><ShieldCheck /><span className="card-index">03</span><h3>Protect every decision</h3><p>Route alerts, preserve audit trails, and keep access aligned with how your teams work.</p><Link href="/security">Explore security <ArrowUpRight size={16} /></Link></article></div></div></section>
    <section className="section flow-section"><div className="container"><div className="split flow-intro"><div><p className="eyebrow">A better payment rhythm</p><h2>From event to evidence.</h2></div><p className="large-copy">Every payment becomes a clear operational record, so teams can move from uncertainty to action without losing the thread.</p></div><div className="flow-line"><div className="flow-step"><span className="flow-icon"><ArrowDownRight /></span><small>01 / Connect</small><strong>Bring every signal together.</strong><p>Mobile money, banks, POS, and internal events in one consistent model.</p></div><div className="flow-step"><span className="flow-icon"><CircleDashed /></span><small>02 / Understand</small><strong>Find the meaningful difference.</strong><p>Normalize, validate, match, and surface exceptions with context.</p></div><div className="flow-step"><span className="flow-icon"><LockKeyhole /></span><small>03 / Act</small><strong>Make the next move accountable.</strong><p>Route alerts, resolve issues, and preserve the evidence behind every outcome.</p></div></div></div></section>
    <section className="section section-lime"><div className="container split"><div><p className="eyebrow">Built for the real world</p><h2>Payment operations are a team sport.</h2></div><div><p className="large-copy">Give finance, operations, risk, and engineering a shared language for what happened and what happens next.</p><Link className="text-link" href="/how-it-works">See how it works <ArrowUpRight size={16} /></Link></div></div></section>
    <section className="section closing-section"><div className="container closing-panel"><div><p className="eyebrow">Ready when your operation is</p><h2>Make trust a system.</h2><p>Give your team the clarity to move faster, investigate better, and close the books with confidence.</p></div><Link className="button button-primary" href="/contact/sales">Start a conversation <ArrowUpRight size={17} /></Link></div></section>
  </>;
}
